language: java
jdk: oraclejdk8

install: true

branches:
  only:
    - master
    
cache:
  directories:
    - $HOME/.gradle

addons:
  sonarcloud:
    organization: "antoineaube-github"

script:
- ./gradlew sonarqube
