language: java
jdk: oraclejdk8

install: true

stages:
- name: snapshot
  if: branch = master
- name: release
  if: branch = release

jobs:
  include:
  - stage: snapshot
    script: ./gradlew build
  - stage: release
    script: ./gradlew build bintrayUpload -x test -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.release=true

cache:
  directories:
    - $HOME/.gradle

addons:
  sonarcloud:
    organization: "antoineaube-github"

script:
- ./gradlew sonarqube
